### ISSUE TITLE
Can you share the ITEGCC tools for this SDK?

### ISSUE THREAD

**Issue by mlpl-peng** [doyaGu/C0501Q_HWJL01#1]
Hi,doyaGu
I have several C0501Q_HWJL01 PCB boards. I want to reprogram the board. I need the ITEGCC tools chain corresponding to this SDK. Can you upload it to GitHub?
ths,
Penn

**Comment by doyaGu** [comment]
You could get it at [this link](https://pan.baidu.com/s/1nv2Tm0T).
